---
- include_vars: '{{ item }}'
  with_first_found:
  - '{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml'
  - '{{ ansible_distribution }}'
  - '{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml'
  - '{{ ansible_os_family }}.yml'
  tags:
  - realmd-install
  - realmd-config
  - realmd-service

- include: install.yml
  tags: realmd_install

- include: config.yml
  tags: realmd_config

- meta: flush_handlers
